apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arch-admin-role
  namespace: arch-namespace
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services", "configmaps", "pods", "secrets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: arch-admin
  namespace: arch-namespace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arch-admin-binding
  namespace: arch-namespace
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: arch-admin
  namespace: arch-namespace
- kind: ServiceAccount
  apiGroup: ""
  name: default
  namespace: arch-namespace
roleRef:
  kind: Role
  apiGroup: ""
  name: arch-admin-role
