apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arch-namespace
  name: arch-jaeger-deployment
  labels:
    app: arch-jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arch-jaeger
  strategy: {}
  template:
    metadata:
      labels:
        app: arch-jaeger
    spec:
      serviceAccountName: arch-admin
      containers:
        - image: jaegertracing/all-in-one:1.51.0
          name: jaeger-all-in-one
          env:
            - name: spring.cloud.kubernetes.discovery.primary-port-name
              value: otlp-http
          ports:
            - containerPort: 4318
              name: otlp-http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 16686
              name: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: arch-jaeger
  namespace: arch-namespace
  labels:
    app: arch-jaeger
    primary-port-name: otlp-http
spec:
  ports:
    - port: 4317
      name: otlp-grpc
      targetPort: 4317
    - port: 4318
      name: otlp-http
      targetPort: 4318
    - port: 16686
      name: frontend
      targetPort: 16686
      nodePort: 30001
  selector:
    app: arch-jaeger
  type: NodePort
  sessionAffinity: None
