server:
  port: 8081

spring:
  application:
    name: arch-users

  profiles:
    default: dev

  config:
    import: [ "kubernetes:" ]

  cloud:
    kubernetes:
      reload:
        enabled: true
        monitoring-secrets: true
        strategy: shutdown
      config:
        namespace: arch-namespace
        name: ${spring.application.name}
        fail-fast: true